"""Initial migration

Revision ID: eced0438ebec
Revises: 18204d981492
Create Date: 2024-10-15 16:34:06.097329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eced0438ebec'
down_revision: Union[str, None] = '18204d981492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Employees',
    sa.Column('id_employee', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('home_phone', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_employee')
    )
    op.create_table('Provider',
    sa.Column('id_provider', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_of_provider', sa.String(), nullable=False),
    sa.Column('representative', sa.String(), nullable=True),
    sa.Column('speak_to', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_provider')
    )
    op.create_table('Supply',
    sa.Column('id_supply', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_provider', sa.Integer(), nullable=False),
    sa.Column('data_of_supply', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_provider'], ['Provider.id_provider'], ),
    sa.PrimaryKeyConstraint('id_supply')
    )
    op.create_table('Products',
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_supply', sa.Integer(), nullable=False),
    sa.Column('name_of_product', sa.String(), nullable=False),
    sa.Column('specifications', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('purchase_cost', sa.Float(), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_supply'], ['Supply.id_supply'], ),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_table('Orders',
    sa.Column('id_order', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_employee', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('posting_date', sa.DateTime(), nullable=True),
    sa.Column('execution_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['Client.id'], ),
    sa.ForeignKeyConstraint(['id_employee'], ['Employees.id_employee'], ),
    sa.ForeignKeyConstraint(['id_product'], ['Products.id_product'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders')
    op.drop_table('Products')
    op.drop_table('Supply')
    op.drop_table('Provider')
    op.drop_table('Employees')
    op.drop_table('Client')
    # ### end Alembic commands ###
